### ISSUE TITLE
(node:29035) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by RobertLowe** [MetinSeylan/Nestjs-OpenTelemetry#14]
```
(node:29035) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at ServerResponse.header (node_modules/express/lib/response.js:771:10)
    at TraceExceptionFilter.catch (node_modules/@metinseylan/nestjs-opentelemetry/src/Tracing/TraceExceptionFilter.ts:20:16)
    at ExceptionsHandler.invokeCustomFilters (node_modules/@nestjs/core/exceptions/exceptions-handler.js:33:26)
    at ExceptionsHandler.next (node_modules/@nestjs/core/exceptions/exceptions-handler.js:13:18)
    at node_modules/@nestjs/core/router/router-proxy.js:13:35
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
 ```

**Comment by RobertLowe** [comment]
something to do with `HttpInstrumentation`

**Comment by RobertLowe** [comment]
controller has a method that uses `res.render`

**Comment by MetinSeylan** [comment]
@RobertLowe can you upgrade the library version to `2.0.0`
