### ISSUE TITLE
this.metricService.getProvider(...).getMeter(...).createObservableGauge is not a function

### ISSUE THREAD

**Issue by kulame** [MetinSeylan/Nestjs-OpenTelemetry#35]
i got a error 

```shell
[Nest] 391906  - 04/27/2022, 10:13:18 AM   ERROR [ExceptionHandler] this.metricService.getProvider(...).getMeter(...).createObservableGauge is not a function
TypeError: this.metricService.getProvider(...).getMeter(...).createObservableGauge is not a function
    at ProcessStartTimeMetric.inject (/srv/apps/npns/npns-service/node_modules/.pnpm/@metinseylan+nestjs-opentelemetry@2.0.7_8a3f4045e53a03a04c90c8adfa35dfce/node_modules/@metinseylan/nestjs-opentelemetry/src/Metric/Metrics/ProcessStartTimeMetric.ts:25:8)
    at InstanceWrapper.useFactory [as metatype] (/srv/apps/npns/npns-service/node_modules/.pnpm/@metinseylan+nestjs-opentelemetry@2.0.7_8a3f4045e53a03a04c90c8adfa35dfce/node_modules/@metinseylan/nestjs-opentelemetry/src/OpenTelemetryModule.ts:93:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Injector.instantiateClass (/srv/apps/npns/npns-service/node_modules/.pnpm/@nestjs+core@8.4.4_b63c269346792a9d57cfab86d23050d2/node_modules/@nestjs/core/injector/injector.js:334:37)
    at callback (/srv/apps/npns/npns-service/node_modules/.pnpm/@nestjs+core@8.4.4_b63c269346792a9d57cfab86d23050d2/node_modules/@nestjs/core/injector/injector.js:48:30)
    at Injector.resolveConstructorParams (/srv/apps/npns/npns-service/node_modules/.pnpm/@nestjs+core@8.4.4_b63c269346792a9d57cfab86d23050d2/node_modules/@nestjs/core/injector/injector.js:122:24)
    at Injector.loadInstance (/srv/apps/npns/npns-service/node_modules/.pnpm/@nestjs+core@8.4.4_b63c269346792a9d57cfab86d23050d2/node_modules/@nestjs/core/injector/injector.js:52:9)
    at Injector.loadProvider (/srv/apps/npns/npns-service/node_modules/.pnpm/@nestjs+core@8.4.4_b63c269346792a9d57cfab86d23050d2/node_modules/@nestjs/core/injector/injector.js:74:9)
    at async Promise.all (index 29)
    at InstanceLoader.createInstancesOfProviders (/srv/apps/npns/npns-service/node_modules/.pnpm/@nestjs+core@8.4.4_b63c269346792a9d57cfab86d23050d2/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
```

**Comment by MetinSeylan** [comment]
#49
