### ISSUE TITLE
The library stop working after update to nest 8

### ISSUE THREAD

**Issue by Motii1** [MetinSeylan/Nestjs-OpenTelemetry#36]
Hi, I have an app that was written in version 6 of nest. I have migrated the app to the nest 8, but now I am receiving an error that I think is connected to the library:

```
[Nest] 1  - 04/28/2022, 10:53:22 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the EventEmitterInjector (?). Please make sure that the argument ModulesContainer at index [0] is available in the OpenTelemetryModule context.

Potential solutions:
- If ModulesContainer is a provider, is it part of the current OpenTelemetryModule?
- If ModulesContainer is exported from a separate @Module, is that module imported within OpenTelemetryModule?
  @Module({
    imports: [ /* the Module containing ModulesContainer */ ]
  })

Error: Nest can't resolve dependencies of the EventEmitterInjector (?). Please make sure that the argument ModulesContainer at index [0] is available in the OpenTelemetryModule context.

Potential solutions:
- If ModulesContainer is a provider, is it part of the current OpenTelemetryModule?
- If ModulesContainer is exported from a separate @Module, is that module imported within OpenTelemetryModule?
  @Module({
    imports: [ /* the Module containing ModulesContainer */ ]
  })

    at Injector.lookupComponentInParentModules (/usr/app/node_modules/@nestjs/core/injector/injector.js:231:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Injector.resolveComponentInstance (/usr/app/node_modules/@nestjs/core/injector/injector.js:184:33)
    at async resolveParam (/usr/app/node_modules/@nestjs/core/injector/injector.js:106:38)
    at async Promise.all (index 0)
    at async Injector.resolveConstructorParams (/usr/app/node_modules/@nestjs/core/injector/injector.js:121:27)
    at async Injector.loadInstance (/usr/app/node_modules/@nestjs/core/injector/injector.js:52:9)
    at async Injector.loadProvider (/usr/app/node_modules/@nestjs/core/injector/injector.js:74:9)
    at async Promise.all (index 3)
    at async InstanceLoader.createInstancesOfProviders (/usr/app/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
    at async /usr/app/node_modules/@nestjs/core/injector/instance-loader.js:29:13
    at async Promise.all (index 9)
    at async InstanceLoader.createInstances (/usr/app/node_modules/@nestjs/core/injector/instance-loader.js:28:9)
    at async InstanceLoader.createInstancesOfDependencies (/usr/app/node_modules/@nestjs/core/injector/instance-loader.js:18:9)
    at async /usr/app/node_modules/@nestjs/core/nest-factory.js:96:17
    at async Function.asyncRun (/usr/app/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)
    at async NestFactoryStatic.initialize (/usr/app/node_modules/@nestjs/core/nest-factory.js:94:13)
    at async NestFactoryStatic.create (/usr/app/node_modules/@nestjs/core/nest-factory.js:37:9)
    at async bootstrap (/usr/app/dist/src/main.js:9:17
```

Does anyone meet similar problem before?

I use `@metinseylan/nestjs-opentelemetry` in version `2.0.0`.

**Comment by Motii1** [comment]
NVM, The solution from https://github.com/MetinSeylan/Nestjs-OpenTelemetry/issues/21 helped. It is duplicate
